"""add cascade delete to featured_request

Revision ID: 468383df9c97
Revises: 5cafc01213f2
Create Date: 2026-05-08 16:32:04.243950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468383df9c97'
down_revision = '5cafc01213f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('featured_request_fundi_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fundi_profile', ['fundi_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('hire_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hire_request_fundi_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fundi_profile', ['fundi_profile_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('profile_update', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profile_update_fundi_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fundi_profile', ['fundi_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_update', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('profile_update_fundi_id_fkey'), 'fundi_profile', ['fundi_id'], ['id'])

    with op.batch_alter_table('hire_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hire_request_fundi_profile_id_fkey'), 'fundi_profile', ['fundi_profile_id'], ['id'])

    with op.batch_alter_table('featured_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('featured_request_fundi_id_fkey'), 'fundi_profile', ['fundi_id'], ['id'])

    # ### end Alembic commands ###
