"""fix hire contractor foreign key

Revision ID: 94895da71e58
Revises: 0999e7b962a1
Create Date: 2026-05-15 08:04:01.319574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94895da71e58'
down_revision = '0999e7b962a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_request', schema=None) as batch_op:
        batch_op.alter_column('contractor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('hire_request_contractor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['contractor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hire_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('hire_request_contractor_id_fkey'), 'contractors', ['contractor_id'], ['id'])
        batch_op.alter_column('contractor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
